[package]
name = "vdisc-core"
version.workspace = true
edition.workspace = true

[dependencies]
image = { version = "0.25.10", default-features = false, features = ["png", "jpeg", "webp"] }
lofty = "0.25.4"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
sha2 = "0.11.0"
symphonia = { version = "0.6.1", features = ["mp3"] }
symphonia-adapter-libopus = "0.3.0"
uuid = { version = "1.26.1", features = ["v4", "serde"] }

[target.'cfg(target_os = "linux")'.dependencies]
cpal = "0.18.2"
libc = "0.2.189"

[dev-dependencies]
hound = "3.5.1"
tempfile = "3"
